
// Generated by https://quicktype.io



export interface AuthI {
  ok:    boolean;
  uid?:   string;
  nombre?:  string;
  email?: string;
  token?: string;
  msg?:  string;
}


export interface Usuario{
  uid: string;
  nombre: string;
  apellido_p?:string;
  apellido_m?:string;
  edad?:number;
  password?: string;
  email?: string;
}
