// Generated by https://quicktype.io

export interface UsuarioInterface {
  ok:       boolean;
  usuarios: Usuario[];
}

export interface Usuario {
  id:           number;
  nombre:       string;
  email:        string;
  edad:         number;
  apellido_p:   string;
  apellido_m:   string;
  password:     string;
  estado:       boolean;
  createdAt:    string;
  updatedAt:    string;
  deletedAt:    null;
  Medicamentos: any[];
}
