export interface VentaI {
  ok:      boolean;
  msg?:string

}

export interface VentaInterface {
  id?: number | string;
  vendedor_id: number | string;
  vendedor:string;
  cliente_id: number;
  cliente:string;
  producto_id: number;
  producto:string;
  precioOriginal:number;
}



export interface body_venta{
  cliente_id?:number;
  vendedor_id?:number | string;
  precio_bruto:number;
  descripcion?:string;
  descuento:number;
  iva:number;
  productos:producto[];
  total:number;
}




export interface producto{
  id:number,
  cantidad:number,
  total:number
}







  // Generated by https://quicktype.io

  export interface VentaAPIInterface {
    ok:    boolean;
    venta: Venta[];
  }

  export interface Venta {
    id:          number;
    producto_id: number;
    factura_id:  number;
    cantidad:    number;
    total:       number;
    createdAt:   Date;
    updatedAt:   Date;
    deletedAt:   Date | null ;
    Factura:     Factura;
    Medicamento: Medicamento | null;
  }

  export interface Factura {
    id:    number;
    total: number;
  }

  export interface Medicamento {
    id:                number;
    nombre_registrado: NombreRegistrado;
  }

  export enum NombreRegistrado {
    LoratadinaAC = "loratadina ac",
    Paracetamol = "paracetamol",
    Salbutamol = "Salbutamol",
  }
